CREATE DATABASE ZomatoDB;
GO

USE ZomatoDB;
GO

-- RESTAURANT
CREATE TABLE RESTAURANT (
    RESTAURANT_ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(15),
    EMAIL VARCHAR(100),
    CITY VARCHAR(50),
    AREA VARCHAR(50),
    RATING DECIMAL(2,1) CHECK (RATING BETWEEN 0 AND 5),
    CREATED_DATE DATETIME DEFAULT GETDATE()
);

-- CATEGORY
CREATE TABLE CATEGORY (
    CATEGORY_ID INT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(200)
);

-- DELIVERY_PERSON
CREATE TABLE DELIVERY_PERSON (
    DELIVERY_ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(15) UNIQUE,
    VEHICLE_NO VARCHAR(20),
    STATUS VARCHAR(10) DEFAULT 'AVAILABLE'
        CHECK (STATUS IN ('AVAILABLE','BUSY'))
);

-- CUSTOMER
CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    FULL_NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(15) UNIQUE,
    EMAIL VARCHAR(100) UNIQUE,
    GENDER CHAR(1) CHECK (GENDER IN ('M','F','O')),
    REGISTRATION_DATE DATETIME DEFAULT GETDATE()
);

-- ADDRESS
CREATE TABLE ADDRESS (
    ADDRESS_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    HOUSE_NO VARCHAR(20),
    STREET VARCHAR(100),
    CITY VARCHAR(50),
    PINCODE VARCHAR(10),
    ADDRESS_TYPE VARCHAR(10)
        CHECK (ADDRESS_TYPE IN ('HOME','OFFICE','OTHER')),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

-- RESTAURANT_CATEGORY (Many-to-Many Bridge)
CREATE TABLE RESTAURANT_CATEGORY (
    RESTAURANT_ID INT,
    CATEGORY_ID INT,
    PRIMARY KEY (RESTAURANT_ID, CATEGORY_ID),
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(RESTAURANT_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

-- MENU
CREATE TABLE MENU (
    MENU_ID INT PRIMARY KEY,
    RESTAURANT_ID INT,
    MENU_NAME VARCHAR(100),
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(RESTAURANT_ID)
);

-- MENU_ITEM
CREATE TABLE MENU_ITEM (
    ITEM_ID INT PRIMARY KEY,
    MENU_ID INT,
    ITEM_NAME VARCHAR(100) NOT NULL,
    PRICE DECIMAL(8,2) CHECK (PRICE > 0),
    AVAILABLE_STATUS VARCHAR(5) DEFAULT 'YES'
        CHECK (AVAILABLE_STATUS IN ('YES','NO')),
    FOREIGN KEY (MENU_ID) REFERENCES MENU(MENU_ID)
);

-- ORDERS
CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    RESTAURANT_ID INT,
    DELIVERY_ID INT,
    ORDER_DATE DATETIME DEFAULT GETDATE(),
    TOTAL_AMOUNT DECIMAL(10,2) CHECK (TOTAL_AMOUNT >= 0),
    ORDER_STATUS VARCHAR(10) DEFAULT 'PLACED'
        CHECK (ORDER_STATUS IN ('PLACED','ONWAY','DELIVERED','CANCELLED')),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(RESTAURANT_ID),
    FOREIGN KEY (DELIVERY_ID) REFERENCES DELIVERY_PERSON(DELIVERY_ID)
);

-- ORDER_ITEM (Composite PK)
CREATE TABLE ORDER_ITEM (
    ORDER_ID INT,
    ITEM_ID INT,
    QUANTITY INT CHECK (QUANTITY > 0),
    PRICE DECIMAL(8,2) CHECK (PRICE > 0),
    PRIMARY KEY (ORDER_ID, ITEM_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES MENU_ITEM(ITEM_ID)
);

-- PAYMENT
CREATE TABLE PAYMENT (
    PAYMENT_ID INT PRIMARY KEY,
    ORDER_ID INT,
    PAYMENT_MODE VARCHAR(10)
        CHECK (PAYMENT_MODE IN ('CARD','CASH','UPI')),
    PAYMENT_DATE DATETIME DEFAULT GETDATE(),
    AMOUNT DECIMAL(10,2) CHECK (AMOUNT >= 0),
    PAYMENT_STATUS VARCHAR(10) DEFAULT 'PENDING'
        CHECK (PAYMENT_STATUS IN ('SUCCESS','FAILED','PENDING')),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

-- REVIEW
CREATE TABLE REVIEW (
    REVIEW_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    RESTAURANT_ID INT,
    RATING INT CHECK (RATING BETWEEN 1 AND 5),
    COMMENTS VARCHAR(300),
    REVIEW_DATE DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(RESTAURANT_ID)
);


SELECT * FROM RESTAURANT;
SELECT * FROM CATEGORY;
SELECT * FROM CUSTOMER;
SELECT * FROM MENU;
SELECT * FROM MENU_ITEM;
SELECT * FROM ORDERS;








SELECT * FROM INFORMATION_SCHEMA.TABLES;
